-- Migration: 0013_fix_scenes_table.sql

ALTER TABLE public.scenes
ADD COLUMN IF NOT EXISTS scene_index INT,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
